In [5]:

from tensorflow.keras.preprocessing.text import one_hot

In [7]:
##sentences 
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of the word',
    'udemy courses are good'
]

In [8]:
#vocabulary size

voc_size = 10000

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of the word',
 'udemy courses are good']

In [9]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8082, 613, 8526, 8116],
 [8082, 613, 8526, 9849],
 [8082, 465, 8526, 7141],
 [4624, 3209, 5662, 4452, 3268],
 [4624, 3209, 5662, 4452, 2247],
 [9703, 8082, 4686, 8526, 8082, 9478],
 [7982, 5166, 7117, 4452]]

In [11]:
##word embedding representation 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences

In [12]:
sent_length = 8
embeded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embeded_docs

array([[   0,    0,    0,    0, 8082,  613, 8526, 8116],
       [   0,    0,    0,    0, 8082,  613, 8526, 9849],
       [   0,    0,    0,    0, 8082,  465, 8526, 7141],
       [   0,    0,    0, 4624, 3209, 5662, 4452, 3268],
       [   0,    0,    0, 4624, 3209, 5662, 4452, 2247],
       [   0,    0, 9703, 8082, 4686, 8526, 8082, 9478],
       [   0,    0,    0,    0, 7982, 5166, 7117, 4452]], dtype=int32)

In [13]:
##feature representation 

dim = 10

In [ ]:
##embedding model
from tensorflow.keras.layers import Input

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [ 8.9507177e-04, -2.3982907e-02, -3.2199658e-02, -1.0150231e-02,
         -1.7943837e-02,  1.5696589e-02,  2.4223100e-02, -6.0265176e-03,
          3.9727736e-02,  3.3321384e-02],
        [-4.4568241e-02, -3.0723326e-03,  1.2044918e-02,  2.

In [24]:
embeded_docs[0]

array([   0,    0,    0,    0, 8082,  613, 8526, 8116], dtype=int32)

In [27]:
model.predict(embeded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 631ms/step


array([[[-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [-5.7853758e-05,  5.1724911e-04,  8.0927126e-03,  3.2548904e-03,
          1.6220797e-02,  4.0507317e-03, -2.2768974e-02,  3.0194391e-02,
         -4.1993797e-02,  3.2597613e-02],
        [ 8.9507177e-04, -2.3982907e-02, -3.2199658e-02, -1.0150231e-02,
         -1.7943837e-02,  1.5696589e-02,  2.4223100e-02, -6.0265176e-03,
          3.9727736e-02,  3.3321384e-02],
        [-4.4568241e-02, -3.0723326e-03,  1.2044918e-02,  2.